### ISSUE TITLE
Not working with iCloud directories, No such file or directory

### ISSUE THREAD

**Issue by BaksiLi** [hscgavin/autopep8-on-pycharm#2]
I had configured as what the instruction said, and it worked normally with the files under the local directory. However, I tried to use autopep8 when I was **working under iCloud directory**, i.e. `/Users/user/Library/Mobile Documents/com~apple~CloudDocs/`, the following **error occurs**:
``` 
/usr/local/bin/autopep8 --in-place --aggressive --aggressive /Users/user/Library/Mobile Documents/com~apple~CloudDocs/try.py
[Errno 2] No such file or directory: '/Users/user/Library/Mobile'
[Errno 2] No such file or directory: 'Documents/com~apple~CloudDocs/try.py'
```  
which I think the terminal misunderstood the directory, since usually a directory with spaces involved is typed as `Mobile\ Documents`.

Can anyone help me to solve this?

(Nevertheless, in the configuration of External Tools in Pycharm, the path is automatically set by an argument `$FilePath$`, which I think may be we should ask for Pycharm to modify this somehow?)

**Comment by hscgavin** [comment]
@LiSongcheng What version of pycharm are you using? If it is not the latest version probably could upgrade it and try it again?
